# Generated by Django 4.1 on 2023-04-28 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('donut_app', '0004_alter_donut_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donut',
            name='name',
        ),
        migrations.RemoveField(
            model_name='donut',
            name='title',
        ),
    ]
