# Generated by Django 4.1 on 2023-04-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('donut_app', '0006_donut_name_donut_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donut',
            name='name',
            field=models.CharField(default='New Donut', max_length=400),
        ),
    ]
