# Generated by Django 4.1 on 2023-04-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('donut_app', '0007_alter_donut_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donut',
            name='allergens',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='donut',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='donut',
            name='ingredients',
            field=models.TextField(max_length=400),
        ),
    ]
